### ISSUE TITLE
WMSCapabilitiesReader read method doesn't work if response contains BOM

### ISSUE THREAD

**Issue by drnextgis** [geopython/OWSLib#256]
Trying to call `read` method of `WMSCapabilitiesReader` and get:

```
XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```

**Comment by roomthily** [comment]
Will be sure to include it for WMS 1.3.0 support (#223) although it should be handled across any of the XML responses.

FYI: I am hoping to have another round ready end of this week. If anyone knows of a real-world service with custom dimensions defined, I am all ears. Otherwise, I'm running from the spec in the GetMap params :(. 

Cheers.

**Comment by roomthily** [comment]
See https://github.com/b-cube/OWSLib/commit/5bb21b62df11ab899058c519f98492d81040f364 for the BOM handling in util.py and https://github.com/b-cube/OWSLib/commit/fc3e71c35d45cbb36f644fb48b6739a7a0a22448 for the CapabilitiesReader update.

If there are thoughts, let me know.

**Comment by cehbrecht** [comment]
See also #408 and #474.
