### ISSUE TITLE
owslib 0.15 broke my workflow

### ISSUE THREAD

**Issue by rsignell-usgs** [geopython/OWSLib#389]
Cell [6] works with owslib=0.14.0, but is broken with owslib=0.15.0, shown here:
https://gist.github.com/anonymous/bda8bc1a8ecf9fbac97c50e9e9df3c08

I'm now getting:
```
RuntimeError: Document is XML, but not CSW-ish
```
on my pycsw 2.1 endpoint:
https://gamone.whoi.edu/csw

**Comment by tomkralidis** [comment]
@rsignell-usgs the problem is with the CSW service configuration and provision.  https://gamone.whoi.edu/csw?request=GetCapabilities&version=2.0.2&service=CSW shows the URL in `ows:OperationsMetadata` as http://gamone.whoi.edu.

It looks like there a redirect at the server level that doesn't pass along the request per se.

In this specific case the default request from the CSW (pycsw 2+ instance) returns a CSW 3.0 Capabilities XML response, which OWSLib doesn't support.

**Comment by rsignell-usgs** [comment]
I was able to get my endpoint working by changing the `url` line in my pycsw config file from:
```
url=http://gamone.whoi.edu/csw
```
to
```
url=https://gamone.whoi.edu/csw
```
