### ISSUE TITLE
WCS WebCoverageService authentication support?

### ISSUE THREAD

**Issue by afrigeri** [geopython/OWSLib#412]
Hello,  is there some way to include authentication  in the WebCoverageService class, like username and password parameters as  in WebMapService_1_1_1?

Thanks 

Alessandro

**Comment by amirmohammadmir** [comment]
Hi. Did you find the answer?
Thanks

**Comment by tomkralidis** [comment]
You can now add an [Authentication ](https://github.com/geopython/OWSLib/blob/master/owslib/util.py#L832)object as follows:

```python
from owslib.wcs import WebCoverageService
w = WebCoverageService('https://example.org/wcs', Authentication(username='foo', password='bar')
```

**Comment by amirmohammadmir** [comment]
@tomkralidis  Unfortunately the [website](https://maps.isric.org/) I'm trying to connect is not working . I check your solution after that.

**Comment by amirmohammadmir** [comment]
Here is the completed code (thanks to @tomkralidis): 
```
from owslib.util import Authentication
from owslib.wcs import WebCoverageService
wcs = WebCoverageService('http://maps.isric.org/mapserv?map=/map/phh2o.map', auth=Authentication(username='foo', password='bar'),
                         version='1.0.0')

bbox = (-1784000, 1356000, -1140000, 1863000)
response = wcs.getCoverage(
    identifier='phh2o_0-5cm_mean',
    crs='urn:ogc:def:crs:EPSG::152160',
    bbox=bbox,
    resx=250, resy=250,
    format='GEOTIFF_16')
with open('./data/Senegal_pH_0-5_mean.tif', 'wb') as file:
    file.write(response.read())

import rasterio
CEC = rasterio.open("./data/Senegal_pH_0-5_mean.tif", driver="GTiff")

from rasterio import plot
plot.show(CEC, title='Mean pH between 0 and 5 cm deep in Senegal', cmap='gist_ncar')
```

1 problem:

1. It gives me this error (do to the server errors):
`requests.exceptions.ReadTimeout: HTTPConnectionPool(host='maps.isric.org', port=80): Read timed out. (read timeout=30)
`
For now, I cannot create a username and password and check if this works or not.

**Comment by amirmohammadmir** [comment]
The servers work just fine for now. I have a new problem and would appreciate any help from you,

Following [this](https://git.wur.nl/isric/soilgrids/soilgrids.notebooks/-/blob/master/02-WCS-getExtent.ipynb) code, my problem is with Authentication procedure. I add an Authentication object to the WebCoverageService object. So, I did as required. Here is the working code with the repaired servers:

```
from owslib.util import Authentication
from owslib.wcs import WebCoverageService
wcs = WebCoverageService('https://maps.isric.org/mapserv?map=/map/phh2o.map', auth=Authentication(username='foo', password='bar'),
                         version='1.0.0')

bbox = (-1784000, 1356000, -1140000, 1863000)
response = wcs.getCoverage(
    identifier='phh2o_0-5cm_mean',
    crs='urn:ogc:def:crs:EPSG::152160',
    bbox=bbox,
    resx=250, resy=250,
    format='GEOTIFF_16')
with open('./data/Senegal_pH_0-5_mean.tif', 'wb') as file:
    file.write(response.read())

import rasterio
CEC = rasterio.open("./data/Senegal_pH_0-5_mean.tif", driver="GTiff")

from rasterio import plot
plot.show(CEC, title='Mean pH between 0 and 5 cm deep in Senegal', cmap='gist_ncar')
```
However, I could not find a way to create a username and password in the https://maps.isric.org/ web service so that I can pass them to the Authentication object I created. Could you please tell me how to do this?

**Comment by amirmohammadmir** [comment]
> Here is the completed code (thanks to @tomkralidis):
> 
> ```
> from owslib.util import Authentication
> from owslib.wcs import WebCoverageService
> wcs = WebCoverageService('http://maps.isric.org/mapserv?map=/map/phh2o.map', auth=Authentication(username='foo', password='bar'),
>                          version='1.0.0')
> 
> bbox = (-1784000, 1356000, -1140000, 1863000)
> response = wcs.getCoverage(
>     identifier='phh2o_0-5cm_mean',
>     crs='urn:ogc:def:crs:EPSG::152160',
>     bbox=bbox,
>     resx=250, resy=250,
>     format='GEOTIFF_16')
> with open('./data/Senegal_pH_0-5_mean.tif', 'wb') as file:
>     file.write(response.read())
> 
> import rasterio
> CEC = rasterio.open("./data/Senegal_pH_0-5_mean.tif", driver="GTiff")
> 
> from rasterio import plot
> plot.show(CEC, title='Mean pH between 0 and 5 cm deep in Senegal', cmap='gist_ncar')
> ```
> 
> 1 problem:
> 
> 1. It gives me this error (do to the server errors):
>    `requests.exceptions.ReadTimeout: HTTPConnectionPool(host='maps.isric.org', port=80): Read timed out. (read timeout=30) `
>    For now, I cannot create a username and password and check if @tomkralidis's solution works or not.

The servers work just fine for now. I have a new problem and would appreciate any help from you,

Following this code, my problem is with Authentication procedure. I add an Authentication object to the WebCoverageService object. So, I did as required. Here is the working code with the repaired servers:

from owslib.util import Authentication
from owslib.wcs import WebCoverageService
wcs = WebCoverageService('https://maps.isric.org/mapserv?map=/map/phh2o.map', auth=Authentication(username='foo', password='bar'),
                         version='1.0.0')

bbox = (-1784000, 1356000, -1140000, 1863000)
response = wcs.getCoverage(
    identifier='phh2o_0-5cm_mean',
    crs='urn:ogc:def:crs:EPSG::152160',
    bbox=bbox,
    resx=250, resy=250,
    format='GEOTIFF_16')
with open('./data/Senegal_pH_0-5_mean.tif', 'wb') as file:
    file.write(response.read())

import rasterio
CEC = rasterio.open("./data/Senegal_pH_0-5_mean.tif", driver="GTiff")

from rasterio import plot
plot.show(CEC, title='Mean pH between 0 and 5 cm deep in Senegal', cmap='gist_ncar')
However, I could not find a way to create a username and password in the https://maps.isric.org/ web service so that I can pass them to the Authentication object I created. Could you please tell me how to do this?

**Comment by tomkralidis** [comment]
>  However, I could not find a way to create a username and password in the https://maps.isric.org/ web service so that I can pass them to the Authentication object I created. Could you please tell me how to do this?

@amirmohammadmir glad you got this working.  Your question on creating a username/password is outside the scope of OWSLib.  Having said this, I believe @jorgejesus may have an an idea as I think he works on the ISRIC platform.

**Comment by amirmohammadmir** [comment]
> > However, I could not find a way to create a username and password in the https://maps.isric.org/ web service so that I can pass them to the Authentication object I created. Could you please tell me how to do this?
> 
> @amirmohammadmir glad you got this working. Your question on creating a username/password is outside the scope of OWSLib. Having said this, I believe @jorgejesus may have an an idea as I think he works on the ISRIC platform.

Dear @tomkralidis . Thank you for suggesting @jorgejesus. Fortunately, I managed to run the code and get the outputs. Here is the revised version:

```
from owslib.wcs import WebCoverageService
wcs = WebCoverageService('https://maps.isric.org/mapserv?map=/map/phh2o.map',
                         version='1.0.0')

bbox = (-1784000, 1356000, -1140000, 1863000)
response = wcs.getCoverage(
    identifier='phh2o_0-5cm_mean',
    crs='urn:ogc:def:crs:EPSG::152160',
    bbox=bbox,
    resx=250, resy=250,
    format='GEOTIFF_INT16')
with open('./data/Senegal_pH_0-5_mean.tif', 'wb') as file:
    file.write(response.read())

import rasterio
CEC = rasterio.open("./data/Senegal_pH_0-5_mean.tif", driver="GTiff")

from rasterio import plot
plot.show(CEC, title='Mean pH between 0 and 5 cm deep in Senegal', cmap='gist_ncar')

```
