### ISSUE TITLE
Integer row/col failing with wmts.gettile

### ISSUE THREAD

**Issue by acrosby** [geopython/OWSLib#461]
We have found in Cartopy that we need to convert row/col from integers to string representations for the WMTS gettile method. I don't know if this is the intent, or if integers should be expected to work, but I thought I would start an issue here.

We work around in Cartopy with the following change minor change: https://github.com/SciTools/cartopy/pull/1052

**Comment by cehbrecht** [comment]
Could someone using `wmts` give a comment on this issue?

@acrosby 
Would be nice if you could provide a pull-request including a test. See:
https://github.com/geopython/OWSLib/blob/56410931e3234e46a077fb15c436294154c30a0c/tests/test_wmts.py#L12

**Comment by mangecoeur** [comment]
Just run into this trying to use a Mapbox WMTS source in cartopy. It's a simple case of type error - since the string substitution is being done with 'replace' instead of 'format' there is no automatic type conversion from integer to string.

What needs to be clarified is whether row/col arguments are required to be strings to begin with (seems unlikely). If not then this should either use `format` or add a `str` cast.

**Comment by chrisgraf** [comment]
this is probably because gettile is handled differently in RESTful only mode .. I could fix that in my case with appended patch of wmts.py

[owslib_wmts.patch.txt](https://github.com/geopython/OWSLib/files/2654240/owslib_wmts.patch.txt)

**Comment by cehbrecht** [comment]
@chrisgraf Thanks for looking at this :) Please, could you provide a PR. It is easier to review and merge.

**Comment by acrosby** [comment]
Sorry I missed the pings from this thread, thanks for taking a look
